Algoritmo "volume"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2020
Var
// Seção de Declarações das variáveis 
r, a, v: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
r<-12
escreval("Programa do volume")
escreval("O altura é de:")
escreva ("O altura é de:",a)
leia(a)

Fimalgoritmo